// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofkgqenzkvhnydsjwhpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma2dxZW56a3Zobnlkc2p3aHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NTgxNjUsImV4cCI6MjA1NTIzNDE2NX0.mlIWwcyyQXo13uKmcgFwRTdGmPjWqCRKrKed04bqavo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);